### ISSUE TITLE
Criar uma meta a ser atingida via dashboard (equalizador)

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#156]
Uma vez que o sistema já possui uma pré-configuração definida, e já está calculando o resultado do modelo de qualidade, é desejável que o cliente possa definir uma meta a ser atingida na próxima release. Essa meta é definida com base em equalizador, onde as "colunas" do equalizador é uma característica de qualidade.

Vale lembrar que a modificação de uma coluna interfere nas demais colunas, uma vez que há uma correlação entre elas. Esta correção pode ser vista na seguinte matrix:

![image](https://user-images.githubusercontent.com/31013187/178874593-a839a191-72db-4c70-855f-11895026ade3.png)

## Tarefas

* Criar o componente do equalizador que será usado para definir a meta
* Modelar a matrix de relação no equalizador, de forma que as modificações nas colunas reflitam nas demais de acordo com a correção

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
