### ISSUE TITLE
Suportar a característica <NAME2>

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#165]
Definir qual será a característica nova que será suportada. Uma vez definido a característica é preciso descobrir quais serão as subcaracterísticas e as medidas que a compõe.

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
