### ISSUE TITLE
Exportar os gráficos em formato de imagem via dashboard

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#167]
É desejável que o usuário consiga exportar em algum formato de imagem os gráficos gerados/apresentados no dashboard.

**Comment by heronsousa** [comment]
A biblioteca que nós estamos utilizando para a apresentação do gráficos, tem essa feature por padrão. Então essa issue poderia ser uma subtarefa, não?

**Comment by durvalcarvalho** [comment]
> A biblioteca que nós estamos utilizando para a apresentação do gráficos, tem essa feature por padrão. Então essa issue poderia ser uma subtarefa, não?

Poderia, mas vamos manter ela como um épico para facilitar a visualização do roadmap do produto.

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
