### ISSUE TITLE
Visualizar o histórico de valores e o valor atual de uma ou mais métricas via dashboard

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#172]
## Valores históricos
Eu como usuário gostaria de visualizar como os valores de uma ou mais métrica ao decorrer do tempo, em um gráfico de linha. 

Segue um exemplo de possível visualização:

![image](https://user-images.githubusercontent.com/31013187/178861914-e16f01ff-94b7-4753-bda7-ea14315a1280.png)

## Valor atual

Eu como usuário gostaria de visualizar as métricas mais recentes na tela de detalhamento do dashboard.

Um exemplo de como essa informação poderia está disponível é apresentado a seguir:

![image](https://user-images.githubusercontent.com/31013187/178881083-c292d32c-b36e-4e47-8cb4-bc3ec9dab917.png)

## Tarefas
- Backend
  - Modelar a tabela métrica e salvar o resultado do cálculo da métrica
  - Implementar a função da métrica definida
  - Criar um endpoint para servir o histórico de determinada métrica
- Frontend
  - Fazer conexão da api com o front
  - Utilizar o componente de visualização com as métricas

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
