### ISSUE TITLE
Pesquisar por outras fontes de métricas (Jira, Mantis, Jekins, Coverity, ...)

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#173]
O MSG deve suportar que diversas medidas sejam obtidas além das medidas disponíveis no JSON do SonarCube. Dessa forma a API desse suportar que novas medidas sejam coletadas independentemente da fonte. 

Também é interessante que durante a pesquisa por novas fontes de medidas seja descoberto os formatos que essas fontes apresentam tais medidas, pois assim é possível criar um endpoint específico que trata esse formato e diminui o trabalho do cliente do MSG de tratar esse formato e carregar no MSG.

## Tarefas
- Descobrir novas fontes de métricas
- Descobrir os formatos que essas fontes de métricas exportam/disponibilizam seus dados

**Comment by durvalcarvalho** [comment]
Observação: Issue escrita inicialmente por @KiSobral 
![image](https://user-images.githubusercontent.com/31013187/179745582-644dae73-566c-4edd-8a26-d534f8f28168.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
