### ISSUE TITLE
Importar e exportar as pré-configurações de um repositório

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#174]
Esta funcionalidade tem como entendimento a estruturação dos atributos de configuração de repositório em um arquivo próprio. O arquivo pode ser exportado a partir de um repositório e, a partir de um outro repositório com uma configuração diferente, seja importado e utilizado.

O tipo de arquivo pensado para estruturar as configurações é um json.

**Comment by durvalcarvalho** [comment]
Issue escrita inicialmente por @KiSobral 
![image](https://user-images.githubusercontent.com/31013187/179747534-0dd48060-8218-4f8b-a8de-4defa09f5fb2.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
