### ISSUE TITLE
Visualizar como a pré-configuração foi definida ao longo do tempo

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#175]
Eu como usuário do MeasureSoftGram
Gostaria de visualizar como uma pré-configuração de projeto se comportou ao longo do tempo
Pois dessa forma eu poderia ver quais e quando características/subcaracterísticas/medidas foram adicionadas e quais foram seus pesos.
Dessa forma, mudanças arbitrárias para aumentar ou dimunir a "nota" de uma entidade do modelo seria sempre vista.
Além disso, seria interessante saber quem fez a mudança.

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
