### ISSUE TITLE
Criar uma Action do GithubHub que facilita a integração com uma instância do MSG

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#176]
Atualmente para subir dados para o sonarcube é preciso usar um script chamado parser.py. O ideal é que seja disponibilizado uma GithubAction que faça a mágica toda, e que alguém interessado a integrar com o MeasureSoftGram tenha o menor esforço possível.

**Comment by durvalcarvalho** [comment]
Issue escrita inicialmente por: @KiSobral 
![image](https://user-images.githubusercontent.com/31013187/179748556-14be5072-3002-4853-8ad8-a7bdbd9dd08d.png)

**Comment by durvalcarvalho** [comment]
Comentário da issue duplicada 
![image](https://user-images.githubusercontent.com/31013187/178885788-fa8af13e-8e09-42d5-b2f5-0c74e59176f5.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
