### ISSUE TITLE
Criar, atribuir e filtrar tags para uma entidade do sistema

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#177]
Uma ideia que surgiu durante o brainstorming de funcionalidades é o sistema do MSG conseguir filtrar dados dos projetos com base no tipo de software, dessa forma existiria tags que seriam atribuídas para cada projeto.

Uma vez que exista as tags, é desejável que exista um filtro onde é possível obter as métricas de um determinado conjunto de releases, como por exemplo "todas as releases com a major 1 (1.x.x)"

**Comment by durvalcarvalho** [comment]
Issue escrita inicialmente por @KiSobral 
![image](https://user-images.githubusercontent.com/31013187/179748981-c3cdd80a-0d67-4269-b8d8-da41822d635a.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
