### ISSUE TITLE
Visualizar como as metas de um repositório foi definida ao longo do tempo

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#178]
Eu como usuário do MeasureSoftGram
Gostaria de visualizar como as metas de um repositório se comportou ao longo do tempo
Pois dessa forma eu poderia fazer uma análise se as metas estão melhorando ou piorando ao decorrer do tempo.
Eu não gostaria de "perder" o histórico de metas de um repositório, e sim que todas as metas já definidas possam ser visualizadas.

<hr>

Uma vez que o software vai sendo desenvolvido, o normal é que o site do MSG atualiza as métricas e a informação sobre os resultados e as metas de uma release seja perdida, dessa forma seria interessante que por meio do site seja possível visualizar o histório de resultados e metas de um projeto.

Uma boa maneira de entender essa issue é ver o [wayback machine](https://web.archive.org/web/*/https://github.com/) que possui uma barra superior com várias datas. A ideia é permitir que o usuário "volte no tempo/releases" e visualize como estava o dashboard e as metas de uma determinada data/release

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
