### ISSUE TITLE
Criar um mecanismo de coleta ativa de métricas do SonarQube

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#179]
Essa funcionalidade é bem parecida com a atividade de action para recuperar os dados do SonarCube, porém, aqui o MeasureSoftGram é o ator ativo da extração dos dados, e não somente recebe os dados a partir de uma action.

Essa funcionalidade pode ser um endpoint que ativa todo o mecanismo de coleta, em tempo de requisição, ou pode ser algo mais complexo que envolva tarefas agendadas e workers.

**Comment by durvalcarvalho** [comment]
Issue escrita inicialmente por @KiSobral 
![image](https://user-images.githubusercontent.com/31013187/179750087-a880f740-e78d-412b-b574-ea321148181e.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
