### ISSUE TITLE
Informar no momento de definição de uma meta se ela é teoricamente atingível ou não

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#181]
Como Valéria
Desejo visualizar um retorno instantâneo sobre as definições da pré-configuração
Para ver como diferentes entradas a alteram o modelo e, assim, planejar melhor uma configuração de qualidade.

**Comment by durvalcarvalho** [comment]
Issue inicialmente escrita por: @KiSobral 
![image](https://user-images.githubusercontent.com/31013187/179750628-14a199f9-fd8b-4f1d-bde2-54c3e52699de.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
