### ISSUE TITLE
Visualizar as metas e os resultados do modelo no mesmo gráfico de linha

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#184]

**Comment by durvalcarvalho** [comment]
![image](https://user-images.githubusercontent.com/31013187/179751366-60b1b7a6-9a1d-4d42-9313-ccb37b252ffd.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
