### ISSUE TITLE
Exportar todos os JSONs do SonarQube já importados no sistema do MSG

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#186]
Eu como usuário **pesquisador**, 
gostaria de exportar todos os arquivos do SonarQube que o sistema já importou
pois assim eu poderia realizar outros cálculos sobre as métricas contidas desses arquivos e assim comprar com os resultados calculados do MSG

**Comment by durvalcarvalho** [comment]
![image](https://user-images.githubusercontent.com/31013187/179752399-1469aa4f-2efc-4189-b3b0-3955edd6984d.png)

**Comment by durvalcarvalho** [comment]
![image](https://user-images.githubusercontent.com/31013187/179752444-073af92c-c92f-416d-80b8-27970ece2236.png)

**Comment by durvalcarvalho** [comment]
![image](https://user-images.githubusercontent.com/31013187/179752497-9ead4fca-08e0-48f8-aef3-622784755f13.png)

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
