### ISSUE TITLE
Comparar duas releases e suas "notas" calculadas pelo modelo

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#187]
Eu como usuário do sistema 
gostaria de selecionar duas releases candidatas e comprar qual release é melhor sobre o aspecto da qualidade
pois dessa maneira minha escolha seria baseada em dados.

Essa comparação pode ser parcial ou total.

Uma comparação total precisa que ambas as releases tenham a mesma pré-configuração, pois dessa maneira é possível calcular a arvore completa.

Já uma compração parcial compara somente as sub-árvores comuns das releases.

## Tarefas

* [ ] Conversar com o cliente para comprender como visualizar essa comparação
* [ ] Conversar com o cliente para o cálculo dessa comparação deve ser feita

**Comment by KiSobral** [comment]
Devido às classificações contraditórias em torno de épico. Esta issue será fechada por tempo indeterminado para reorganização do escopo do projeto.
