### ISSUE TITLE
Exibir histórico da SQC

### ISSUE THREAD

**Issue by KiSobral** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#223]
Como **Valéria**
Desejo visualizar o histórico da SQC
Para conseguir visualizar de forma analítica as informações agregadas do meu projeto.

**OBS:** O formato de visualização pode ser:
- Tabular
- Gráfico de linha

### Grafico do SQC de um repositório

Blocked by #224 

![image](https://user-images.githubusercontent.com/31555287/188245991-258d3f55-dec9-4fec-94f4-6d85adef8b1a.png)

- [ ] Deve plotar histórico do SQC como gráfico de linha
- [ ] Deve plotar histórico do SQC como gráfico tabular
- [ ] Deve ser possível visualizar o histórico do SQC no grafico do histórico de caracteristicas
- [ ] Ao colocar o ponteiro do mouse em cima de um ponto da linha, deve forncer detalhes do ponto (Todos os valores do ponto que virão do Back-end)
- [ ] Deve ser possível realizar download do gráfico

### Gráfico saúde do projeto

![image](https://user-images.githubusercontent.com/31555287/188247665-ebe51717-94f3-46bc-bc78-ddd513ac945c.png)

- [ ] Deve pegar valores do histórico das metas cadastradas de cada release realizada
- [ ] Deve pegar valores calculados, a partir do equalizador e configurações, em cada release 
- [ ] Valores resgatados do back devem estar sincronizados por release
- [ ] Deve plotar históricos como gráfico de linha

**Comment by durvalcarvalho** [comment]
![image.png](https://images.zenhubusercontent.com/5bbe0ba8c245624f0b833529/fdc86669-84c5-4607-9fb4-674771cefa9e)

**Comment by durvalcarvalho** [comment]
@KiSobral @DanilloGS @heronsousa 
Essa US foi divida nas seguintes US:

- Exibir histórico da SQC na tela de repositório #275 
- Exibir histórico da SQC na tela de produto #274
