### ISSUE TITLE
Habilitar o autocomplete dos comandos e parâmetros do CLI

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#239]
## História de Usuário

Eu como Gustavo
Gostaria de ter a comodidade de escrever apenas parte dos comandos do CLI, logo depois, apertar a tecla TAB, e receber o comando inteiro escrito, sendo completado automaticamente para mim.

## Descrição
Atualmente o usuário precisa digitar todos os caracteres, e o desejável é que a medida que ele for digitado e apertando a tecla TAB o comando seja autocompletado.

## Critérios de aceitação

- [ ] A execução do comando `measuresoftgram impo` + TAB deve autocomplementar para `measuresoftgram import`;
- [ ] A execução do comando `measuresoftgram get metr` + TAB deve autocomplementar para `measuresoftgram get metric`;
- [ ] A execução do comando `measuresoftgram get measu` + TAB deve autocomplementar para `measuresoftgram get measures`;

## Tarefas

- [ ] Fazer um estudo de como habilitar esse autocomplete no CLI.
- [ ] Implementar validando os casos do teste descritos nos critérios de aceitação.

**Comment by lboaventura25** [comment]
Boa tarde, @danieldagerom! 

Lembrando que HU's são descritas utilizando o nome da persona definida no Documento de [Visão do Produto](https://fga-eps-mds.github.io/2022-1-MeasureSoftGram-Doc/#/documentos/visao_do_produto) que mais se encaixa como usuário da funcionalidade. 

É importante ressaltar que são necessários descrever os critérios de aceitação para a HU e as tarefas planejadas para a execução da atividade.

Após finalizadas as etapas, devemos enviar para o cliente poder validar  a HU.
