### ISSUE TITLE
Validar a passagem de parâmetros para get e import no CLI

### ISSUE THREAD

**Issue by andrelucasf** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#249]
## Descrição
Realizar a validação da passagem de parâmetros para as funcionalidade get e import. Caso o usuário digite algo diferente ou inexistente, precisamos indicar para ele da melhor forma o erro.

## Critérios de Aceitação:
- A funcionalidade de get e import continuarem funcionando
- Deve indicar para o usuário o erro da melhor forma
- Deve indicar como utilizar os parâmetros corretos

## Tarefas:
- [x] Indicar para o usuário da melhor forma o erro ao utilizar parâmetros inválidos do comando "get" 
- [x] Indicar para o usuário os parâmetros válidos no get
- [x] Indicar para o usuário da melhor forma o erro ao utilizar parâmetros inválidos do comando "import" 
- [x] Indicar para o usuário os parâmetros válidos no import

**Comment by lboaventura25** [comment]
Show de bola, @andrelucasf 

Utilizando assim, ele já mostra o erro como gostaríamos utilizando as funcionalidades da própria lib `argparser`:

```python
parser_get_entity.add_argument(
    "entity",
    type=str,
    choices=('metrics', 'measures'),
    help=(
        "The entity to get. Valid values are: "
         + ", ".join(AVAILABLE_ENTITIES)
    ),
)
```

Dê uma olhada nesse link aqui, em alguns momentos ele usa o choices e mostra como criar um erro customizado pra CLI.

https://pypi.org/project/argcomplete/
