### ISSUE TITLE
Criar o `Documento de Agenda de Trabalho e Ferramentas`

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#28]

**Comment by durvalcarvalho** [comment]
O que é documento de agenda?

**Comment by heronsousa** [comment]
Não seria a apresentação do horário de trabalho de cada um, quando acontecerá os ritos do time e afins?

**Comment by durvalcarvalho** [comment]
> Não seria a apresentação do horário de trabalho de cada um, quando acontecerá os ritos do time e afins?

Faz sentido, mas acho que antes de fazer, para evitar o retrabalho, seria bom perguntar para o Hilmer
