### ISSUE TITLE
Definir a gerência de configuração 

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#41]
Fluxo de trabalho
Versionamento semântico

**Comment by durvalcarvalho** [comment]
O que é isso?

**Comment by KiSobral** [comment]
Essa issue se trata da escrita dos documentos de políticas de branch, fluxo de trabalhos adotado (no nosso caso, utilizaremos o gitflow) e também do versionamento semântico (a política adotada para numeração de releases)

**Comment by durvalcarvalho** [comment]
> Essa issue se trata da escrita dos documentos de políticas de branch, fluxo de trabalhos adotado (no nosso caso, utilizaremos o gitflow) e também do versionamento semântico (a política adotada para numeração de releases)

Essas tarefas parecem com as tarefas da issue #34 .

**Comment by KiSobral** [comment]
> > Essa issue se trata da escrita dos documentos de políticas de branch, fluxo de trabalhos adotado (no nosso caso, utilizaremos o gitflow) e também do versionamento semântico (a política adotada para numeração de releases)
> 
> Essas tarefas parecem com as tarefas da issue #34 .

São parecidas mas são documentos um pouco diferentes. A issue #34 envolve a criação do documento de como contribuir, licença e afins, e esse documento tem mais a ver com as políticas do controle de versão.
