### ISSUE TITLE
Repensar os pipeline dos projetos

### ISSUE THREAD

**Issue by durvalcarvalho** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#57]
Atualmente os pipelines dos projetos core e service estão realizando as seguintes atividades:

#### `docker-push.yml`: 

* Builda uma imagem e sobe para o dockerhub.
* Esse atividade é executada somente quando há um release. 
* É desejável que sempre que commits forem feitos nas branches de homologação e de produção uma imagem seja buildada.

#### `linter.yml`
* Aplicação do linter no código do projeto [OK]

#### `test.yml`: 
* Esse pipeline realiza as seguintes tarefas (que deveria ser separadas):
* Execução dos testes e upload para o CodeCov
* Análise do SonarCube

#### `metrics.yml`: 
* Esse é o pipeline que "coleta" os dados do sonarcube.
* Atualmente é uma abordagem bastante tosca, onde os dados obtidos no sonarcube são escrito em um arquivo e esse arquivo é comitado no repositório de documentação ([esse aqui](https://github.com/fga-eps-mds/2021-2-MeasureSoftGram-Doc/tree/main/analytics-raw-data))
* O ideal é que fosse criado uma action que apontasse para uma instância do MeasureSoftGram e os dados fossem enviados via api para o serviço

**Comment by igor-paiva** [comment]
> Atualmente os pipelines dos projetos core e service estão realizando as seguintes atividades:
> 
> #### `docker-push.yml`:
> * Builda uma imagem e subindo para o dockerhub.
> * Esse atividade é executada somente quando há um release.
> * É desejável que sempre que commits forem feitos nas branches de homologação e de produção uma imagem seja buildada.
> 
> #### `linter.yml`
> * Aplicação do linter no código do projeto [OK]
> 
> #### `test.yml`:
> * Esse pipeline realiza as seguintes tarefas (que deveria ser separadas):
> * Execução dos testes e upload para o CodeCov
> * Análise do SonarCube
> 
> #### `metrics.yml`:
> * Esse é o pipeline que "coleta" os dados do sonarcube.
> * Atualmente é uma abordagem bastante tosca, onde os dados obtidos no sonarcube são escrito em um arquivo e esse arquivo é comitado no repositório de documentação ([esse aqui](https://github.com/fga-eps-mds/2021-2-MeasureSoftGram-Doc/tree/main/analytics-raw-data))
> * O ideal é que fosse criado uma action que apontace para uma instância do MeasureSoftGram e os dados fossem enviados via api para o serviço

Aproveitar que vi essa issue e tecer alguns comentários para evitar confusão.

Sobre a action de testes ela realiza essas duas tarefas para que seja enviado corretamente para o SonarCloud todas as medidas de testes (testes executados, testes com sucesso, testes com falhas e erros e cobertura), existe um grande problema com essa integração e isso gerou muitos problemas em vários grupos.

Essa abordagem "tosca" da action de métricas foi um requisito da disciplina. Todos os grupos precisavam coletar as métricas e salvar no repositório de DOCS. Vale alinhar com o professor se não será necessário fazer isso esse semestre. É importante ressaltar que as métricas analisadas pelo MeasureSoftGram são inseridas via CLI (através do comando `import`) e essas métricas extraídas na action são do próprio projeto e são analisadas atráves do notebook de analytics (outro requisito da disciplina). Resumindo: disciplina != produto.

O projeto tá na mão de vocês, sigam com a abordagem que acharem melhor, mas fazendo esses comentários tentando ajudar a entender a razão de algumas dessas coisas.
