### ISSUE TITLE
Migrar o serviço `service` e `core` para outro framework

### ISSUE THREAD

**Issue by lboaventura25** [fga-eps-mds/2022-1-MeasureSoftGram-Doc#97]
## Descrição
Os serviços `service` e `core` foram implementados utilizando o micro-framework Flask e o banco de dados não relacional mongodb. Essa escolha se mostrou ineficiente devido a ausência de funcionalidades disponíveis no Flask e a ausência de queries de agregação em bancos de dados não relacionais. 

Devido a esses motivos, foi decidio migrar a base de código existente para um framework que agregue mais funcionalidades e evite que os desenvolvedores implemente funcionalidades básicas (controle de login, telas administrativas, serialização de jsons e ORMs) 

## Critérios de Aceitação:
Para esse tipo de migração é necessário uma tecnologia com:

- Suporte a criação de CRUDS,
- Gerenciamento de banco de dados relacional.
- Criação das models.
- Suporte a serialização de JSONs
- Autenticação 
- Paineis administrativos

É desejável o framework utiliza a linguagem Python, uma vez que isso irá facilitar o porte de códigos existentes.

## Tarefas:

- [x] Estudar quais são os melhores frameworks para os requisitos desejados.
- [x] Definir o novo framework a ser utilizado no projeto.
- [x] Criar as migrations do `service`
- [ ] Migrar o código o serviço `service`

**Comment by durvalcarvalho** [comment]
Foi decidido usar o framework Django Rest Framework pelos seguintes motivos:
* O framework disponibiliza telas administrativas para facilitar a análise e cadastro de dados no banco de dados
* O framework possui implementado o padrão de projeto Singleton, Factory Method e Observer, o que diminui más práticas como duplicação de código, side-effects, circular import
*  ORM simples e com muita documentação

**Comment by durvalcarvalho** [comment]
![image](https://user-images.githubusercontent.com/31013187/178615944-d999f1aa-3d2e-44ee-a35d-b8dc12f931c0.png)

**Comment by durvalcarvalho** [comment]
O Core foi mantido em flask
